// Build information, automatically generated by `ng-info`
const build = {
    version: "0.0.0",
    timestamp: "Tue Dec 21 2021 16:48:39 GMT+0600 (Bangladesh Standard Time)",
    message: null,
    git: {
        user: "hannan",
        branch: "master",
        hash: "5db96c",
        fullHash: "5db96cba9d09cdd6fe176df4a8fa0834b057f018"
    }
};

export default build;